
[functions]
[functions.stripe-connect]
verify_jwt = false

[functions.stripe-payment]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-subscriptions]
verify_jwt = false
