
project_id = "wkspjzbybjhvscqdmpwi"

[api]
enabled = true
url = "https://wkspjzbybjhvscqdmpwi.supabase.co"
service_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indrc3BqemJ5YmpodnNjcWRtcHdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2MTcwODYsImV4cCI6MjA1NDE5MzA4Nn0.q4hsuWLxoB81E7UzgFiCMesq4aPhIFTYWZMJMjjDmU0"

[functions]
[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-webhook-simple]
verify_jwt = false
