
[functions]
[functions.qbo-token]
verify_jwt = false

[functions.qbo-refresh]
verify_jwt = false

[functions.qbo-test-connection]
verify_jwt = false

[functions.qbo-data-operation]
verify_jwt = false

[functions.stripe-connect]
verify_jwt = false

[functions.stripe-payment]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-subscriptions]
verify_jwt = false
