
project_id = "wkspjzbybjhvscqdmpwi"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "extensions", "realtime", "pg_graphql", "supabase_functions"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323
enabled = true

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:5173"

[auth.email]
enabled = true
double_confirm_changes = true
double_confirm_deletions = true

[analytics]
enabled = true

[experimental]
postgres_ssl_certs = false

[functions.authkit-token]
import_map = "./supabase/functions/authkit-token/import_map.json"
