# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "cnstrct"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# Maximum rows returns in a single REST request.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[db.pooler]
enabled = false
# Port to use for the local connection pooler.
port = 54329
# Specifies when a server connection can be reused by other clients.
# Configure one of the supported pooler modes: `transaction`, `session`.
pool_mode = "transaction"
# How many server connections to allow per user/database pair.
default_pool_size = 20
# Maximum number of client connections allowed.
max_client_conn = 100

[realtime]
enabled = true
# Bind realtime via either IPv4 or IPv6. (default: IPv6)
# ip_version = "IPv6"

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://localhost"

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 54325
# pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Defaults to 10 seconds.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Configure one of the supported SMS providers: `twilio`, `messagebird`, `textlocal`, `vonage`.
[auth.sms]
enable_signup = true
enable_confirmations = true
# provider = "twilio"
# Account SID for Twilio
# account_sid = ""
# Auth token for Twilio
# auth_token = ""
# Messaging service for Twilio
# messaging_service_sid = ""

# Use pre-defined map of phone number to OTP for testing.
[auth.sms.test_otp]
# 4152127777 = "123456"

# Configure storage for media uploads to Storage bucket.
[storage.buckets]
# enabled = true # Removed this line as it expects a map/table of buckets, not a boolean.

# Configure email delivery for authentication emails.
[auth.email.template.invite]
subject = "You have been invited"
# content_path = "supabase/templates/invite.html"

[auth.email.template.confirmation]
subject = "Confirm Your Signup"
# content_path = "supabase/templates/confirmation.html"

[auth.email.template.recovery]
subject = "Reset Your Password"
# content_path = "supabase/templates/recovery.html"

[auth.email.template.magic_link]
subject = "Your Magic Link"
# content_path = "supabase/templates/magic_link.html"

[auth.email.template.email_change]
subject = "Confirm Email Change"
# content_path = "supabase/templates/email_change.html"

[auth.email.template.sms_otp]
# content_path = "supabase/templates/sms_otp.html"

[auth.email.template.sms_verification]
# content_path = "supabase/templates/sms_verification.html"

# Specify a custom function for SMS OTP verification.
# [auth.hooks.custom_access_token]
# enabled = true
# uri = "pg-functions://postgres/custom_access_token"

# These are functions that can be called from the client using the Storage API.
# [functions.download]
# verify_jwt = true

# [functions.upload]
# verify_jwt = true

# You can also disable verification for specific edge functions.
[functions.stripe-webhook]
verify_jwt = false

# Mark other edge functions as public or requiring authentication.
[functions.stripe-subscriptions]
verify_jwt = true
